version: '3'
services:
  node-exporter:
    image: prom/node-exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.textfile.directory=/etc/node-exporter/textfile_collector
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/node-exporter/textfile_collector:/etc/node-exporter/textfile_collector:ro
    ports:
      - "9100:9100"
    restart: always

  grafana-agent:
    image: grafana/agent:latest
    volumes:
      - /etc/grafana/agent/agent-config.yaml:/etc/grafana/agent/agent-config.yaml
    ports:
      - "9101:9091"
    restart: always
